[package]
name = "scrollscope"
version = "0.1.0"
edition = "2021"
authors = ["Ardura <azviscarra@gmail.com>"]
license = "GPL-3.0-or-later"
homepage = "https://github.com/ardura"
description = "A simple scrolling oscilloscope"

[workspace]
members = ["xtask"]

[lib]
crate-type = ["cdylib","lib"]

[dependencies]
atomic_float = "0.1"
egui = "0.21.0"
nih_plug = { path = "../nih-plug-master", features = ["assert_process_allocs","standalone"] }
nih_plug_egui = { path = "../nih-plug-master/nih_plug_egui" }
queues = "1.1.0"

[profile.release]
lto = "thin"
strip = "symbols"

[profile.profiling]
inherits = "release"
opt-level = 2
debug = true
strip = "none"
